{"name": "Existent user login with invalid data", "status": "passed", "description": "User login with invalid credentials, expected error", "parameters": [{"name": "payload", "value": "{'email': 'test-data_sm@yandex.ru', 'password': 'password1'}"}], "start": 1705960205728, "stop": 1705960205895, "uuid": "9d49a34a-19d4-47a5-a972-c495c0f14dc6", "historyId": "5e8b01ca7f496d724c4db6b85367efd6", "testCaseId": "2a3ceab4523bcc7d8a79fdadae107be4", "fullName": "tests.test_login.TestLoginUser#test_login_invalid_credentials_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-N69F3B6"}, {"name": "thread", "value": "11152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}