{"name": "Existent user login with invalid data", "status": "passed", "description": "User login with invalid credentials, expected error", "parameters": [{"name": "payload", "value": "{'email': 'test-data_sm3@yandex.ru', 'password': 'password'}"}], "start": 1705960205554, "stop": 1705960205720, "uuid": "5bc6484c-c825-466a-a61b-e0d498533e1a", "historyId": "2d7ded12c918a6d2ab938d8410c29464", "testCaseId": "2a3ceab4523bcc7d8a79fdadae107be4", "fullName": "tests.test_login.TestLoginUser#test_login_invalid_credentials_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-N69F3B6"}, {"name": "thread", "value": "11152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}