{"name": "Get user's orders without authorization", "status": "passed", "description": "User without token, expected error", "start": 1705960204742, "stop": 1705960204910, "uuid": "09e856a0-178d-4e31-a30c-5b827463178f", "historyId": "7d5ec836b3e8efc02228a410d5b55f3c", "testCaseId": "7d5ec836b3e8efc02228a410d5b55f3c", "fullName": "tests.test_get_order.TestGetOrder#test_get_orders_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-N69F3B6"}, {"name": "thread", "value": "11152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}